### ISSUE TITLE
Graceful termination

### ISSUE THREAD

**Issue by Orlha** [kissbeni/tinyhttp#2]
After a quick glance I'm still not sure of a way of graceful termination.
If I call "shutdown" from a separate thread, then I get a segmentation fault inside HttpServer::processRequest in the listening thread.

**Comment by kissbeni** [comment]
I haven touched this code in a while, but I'll find some time during the week to look into this.

**Comment by kissbeni** [comment]
I managed to make graceful shutdown work properly (or at least from my testing it looks like so), it would be great @Orlha if you could try it too in your specific use-case.
